#!/bin/bash
#-----kiritosshxd------
fun_swap() {
    clear
		echo -e "\E[44;1;37m            ADMINISTRAR MEMORIA VIRTUAL             \E[0m"
        echo ""
		echo -e "\033[1;31mSwap es un espacio utilizado para aumentar la cantidad de RAM. \ndel sistema (RECOMENDADO PARA MÁQUINAS CON BAJA RAM).\033[0m"
        echo -e "\033[1;31mAntes de activar, conozca cuánto almacenamiento tiene su máquina, \nDeje siempre suficiente espacio de almacenamiento para evitar accidentes.\033[0m"
        echo ""
		echo -e "\033[1;31m[\033[1;36m1\033[1;31m] \033[1;37m• \033[1;33mACTIVAR SWAP / MODIFICAR VALOR DE SWAP \033[0m"
		echo -e "\033[1;31m[\033[1;36m2\033[1;31m] \033[1;37m• \033[1;33mDESACTIVAR SWAP\033[0m"
		echo -e "\033[1;31m[\033[1;36m0\033[1;31m] \033[1;37m• \033[1;33mREGRESAR\033[0m"
		echo ""
		echo -ne "\033[1;32m QUE DESEA HACER ? \033[1;33m?\033[1;37m "
		read resposta
		if [[ "$resposta" = '1' ]]; then
            clear
			echo -e "\E[44;1;37m            MEMORIA VIRTUAL              \E[0m"
			echo ""
			echo -ne "\033[1;32m¿CUÁNTOS GIGAS QUIERES USAR? \033[1;33m?\033[1;37m: "
			read gigas
            [[ -z "$gigas" ]] && {
					echo ""
					echo -e "\033[1;31mGigas No Validas!"
					sleep 2
					clear
					menu
				}
            echo ""
			echo -e "\033[1;32mINICIANDO MEMORIA VIRTUAL \033[1;31m$gigas GB\033[1;33m"
			echo ""
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            fallocate -l ${gigas}G /bin/ram.img > /dev/null 2>&1
            chmod 600 /bin/ram.img > /dev/null 2>&1
            mkswap /bin/ram.img > /dev/null 2>&1
            swapon /bin/ram.img > /dev/null 2>&1
            echo 50  > /proc/sys/vm/swappiness
            echo '/bin/ram.img none swap sw 0 0' | sudo tee -a /etc/fstab > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mMEMORIA VIRTUAL ACTIVADO CON EXITO\033[1;33m"
            sleep 2
			fun_swap
        elif [[ "$resposta" = '2' ]]; then
            clear
			echo -e "\E[44;1;37m            DESACTIVANDO MEMORIA VIRTUAL              \E[0m"
            swapoff -a
            rm -rf /bin/ram.img > /dev/null 2>&1
            echo ""
			echo -e "\033[1;32mMEMORIA VIRTUAL DESACTIVADO CON EXITO!\033[1;33m"
			sleep 2
			fun_swap
        elif [[ "$resposta" = '0' ]]; then
			echo ""
			echo -e "\033[1;31mRetornando...\033[0m"
			sleep 1
			menu
		else
			echo ""
			echo -e "\033[1;31mOpcion No Valida !\033[0m"
			sleep 1
			fun_swap
		fi 
}
fun_swap
